"""empty message

Revision ID: a073e0f1e7c2
Revises: a67b5a460e7d
Create Date: 2018-08-01 00:41:01.467448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a073e0f1e7c2'
down_revision = 'a67b5a460e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pending_transfers', ['leapfrog_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pending_transfers', type_='unique')
    # ### end Alembic commands ###
